### ISSUE TITLE
Show/Hide button with custom InputDecoration

### ISSUE THREAD

**Issue by francescolodi-vicasystem** [rodrigobastosv/fancy_password_field#14]
It would be great to be able to customize the InputDecoration (for label and hint) without loose the show/hide button, merging the standard suffixIcon in the provided InputDecoration.

**Comment by rodrigobastosv** [comment]
Hello @vicasystem , thanks for using this package! This is a great sugestion.

I saw you created a PR with the changes. There was a lot of stuff going on that PR, including a fancy_password_field folder was created (i think by mistake), so i decided to close that PR.

But i implemented your request, it's already on version 1.0.3 on pub.dev.

Thanks very much!
