### ISSUE TITLE
No right padding on hide password icon

### ISSUE THREAD

**Issue by kterrago18** [rodrigobastosv/fancy_password_field#19]
Thank you for your package.

I think there should be a right padding on hide password icon, same as showpassword icon. When we changing their states, the icon looks moving from right to left.

```
...

class DefaultShowHidePasswordButton extends StatelessWidget {
  ....

  @override
  Widget build(BuildContext context) {
    return Column(
     ...
      children: [
        GestureDetector(
          onTap: _onPressed,
          child: _hidePassword
              ? _hidePasswordIcon ?? // << there should be a padding here as well
                  const FaIcon(
                    FontAwesomeIcons.eye,
                  )
              : Padding(
                  padding: const EdgeInsets.only(right: 6),
                  child: _showPasswordIcon ??
                      const Icon(
                        FontAwesomeIcons.eyeSlash,
                      ),
                ),
        ),
      ],
    );
  }
}
```

**Comment by rodrigobastosv** [comment]
Hey @kterrago18 , thanks for using this package. Sorry for the late reply. I have been very busy.

That totally makes sense, i will adjust this tomorrow. Thanks!

**Comment by rodrigobastosv** [comment]
Hey @kterrago18 , this MR #20 was merged. It makes much more flexible to change the icons as needed. So i guess this will solve your issue.

I am going to close this for now. But feel free to reopen if you feel like you still need help on this.
