### ISSUE TITLE
No validation happens if initialValue or a TextEditingController with a value are provided

### ISSUE THREAD

**Issue by ConradGroth** [rodrigobastosv/fancy_password_field#21]
*Reproduction:*
Create a `FancyPasswordField` with a not-empty `initialValue` and some validation rules. The validations are shown in red, until the first change occurs in the password field.

*Solution:*
In the class `_FancyPasswordFieldState` initialize the `_value` with provided values.

I created PR #22 to solve it. I tested the fix in my local code and it works as expected.

**Comment by rodrigobastosv** [comment]
Fixed in #22 . Closing issue!
