### ISSUE TITLE
How to create block progress indicator for showing strength as shown in the sample?

### ISSUE THREAD

**Issue by Aryan2892** [rodrigobastosv/fancy_password_field#27]
I want to used the block version to display password strength but I dont know which parameter to use and how to achieve it.

**Comment by rodrigobastosv** [comment]
Hey @Aryan2892 , thanks for using this package. You should have by default a Strength indicator. You can leverage the `hasStrengthIndicator` parameter to enable or disable.

**Comment by Aryan2892** [comment]
> Hey @Aryan2892 , thanks for using this package. You should have by default a Strength indicator. You can leverage the `hasStrengthIndicator` parameter to enable or disable.

Hey! Thank you so much for responding. Your package is the most optimal solution to what I need for my app. 
Let me show what exactly I want to achieve 
![image](https://github.com/rodrigobastosv/fancy_password_field/assets/78354139/7988e813-66b4-4f8d-9cac-7f45250f6a09)
![image](https://github.com/rodrigobastosv/fancy_password_field/assets/78354139/047c9182-53f5-4fb4-9900-355cf3b75c63)

Is there a code available for these samples that I can refer to create something similar. I want this spaced strength indicator instead of a continuous one.

**Comment by rodrigobastosv** [comment]
Sure! Check the example folder inside the project. There's a bunch of samples there.

**Comment by Aryan2892** [comment]
I really appreciate you taking time to reply to me. I know this is not the right place to ask but I am a beginner in flutter development and I also have some doubts for flutter web and BloC state management. Can I reach out to you on your email or other medium convenient to you for help?

**Comment by rodrigobastosv** [comment]
Hey man, sure! Hit me up by email and we can discuss these topics. I'm going to close this issue for now!
